### ISSUE TITLE
Neubau des bisherigen ShortURL-Service

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-shorturl#1]
Der bisherige rein Perl-basierte ShortURL-Service auf go.fau.de soll durch ein WordPress-Plugin erstetzt werden.
Die Domain go.fau.de soll in Zukubft durch eine WordPress-Instanz ersetzt werden, auf die das Plugin aktiv ist.

Wichtige Grundlage ist dabei, dass die Generierung der ShortURLs nach gleichem mathematischen Algorithmus erfolgt, wie bisher um vorhandene ShortURLs weiterhin funktionabel zu lassen.
Im Gegensatz zu den bisherigen Verfahren, welches auf Basis von definierter Ziel-Websites, wie das OTRS, vorhandenen alphanumerische Strings in einen kurzen String umwandelt, soll dieser Service es auch erlauben, dass Perosnen, die via SSO eingeloggt sind, individuelle URLs eingeben, zu der sie eine Verkürzung erhalten.

Das Plugin soll daher folgende  DInge ermöglichen:

- [x] #2
- [x] #3
- [x] #5
- [x] #4

Aus Performancegründen kann darüber nachgedacht werden, via WordPress lediglich die Verwaltung und Eingabe/Bearbeitung von ShortURLs zu ermöglichen, die eigentliche Redirection jedoch durch ein PHP-Skript auf einer geeigneten abgespeckten Webspace-Website durchführen zu lassen.

**Comment by thenickless** [comment]
umgesetzt in 0.1.59
