### ISSUE TITLE
ShortURL-Verwaltung für Benutzer

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-shorturl#10]
Die Benutzer, die eigenen ShortURLs anlegen und bearbeiten können, sollen, wenn sie eingeloggt sind, eine minimale Oberfläche erhalten, in der sie sehen, welche ShortURLs sie eingegeben haben, welche Ziele diese haben, etc.

ggf. in Tabellenform mit Anzeige:
- ShortURL
- Ziel-URL
- Anlegedatum
- Gültig bis-Datum
- Kategorie
- Tags

Die Klick auf die ShortURL führt zum Bearbeiten.

**Comment by thenickless** [comment]
umgesetzt in 0.1.59
