### ISSUE TITLE
Umstellung der Domain go.fau.de

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-shorturl#12]
Das Plugin soll auf einer eigenständigen WordPress Instanz eingerichtet werden.
Bei Fertigstellung soll diese Instanz den Domainnamen go.fau.de übernehmen.

Später kann auch dafüber diskutiert werden, ob auch fau.info genutzt wird.

**Comment by thenickless** [comment]
Testserver: 
https://www.go-fau.test.rrze.fau.de

**Comment by thenickless** [comment]
done. 1.4.1
