### ISSUE TITLE
Extend validity automatically for actively used shorturls

### ISSUE THREAD

**Issue by m-w** [RRZE-Webteam/rrze-shorturl#120]
Currently there's a fixed limit of one year for the validity of the shortened urls. Instead of having to email the webmasters ([see Q&A](https://www.shorturl.rrze.fau.de/faqs/#ID-53)) it would be nice if validity is extended automatically based on the last usage.

This will have several advantages:

- the database is still cleaned up from unused codes,
- no-one needs to worry about the validity period (e.g. QR can be used on prints),
- actively used short urls will not change (e.g. when used in Q&A templates).

I'd like to suggest an automated extension of the validity by one year from the last usage date.

**Comment by thenickless** [comment]
Thank you for your suggestion!
We will set the limit to unlimited, consider a given date and install a cronjob to clean all links that lead to HTTP 4xxx soon.
