### ISSUE TITLE
neuer Cronjob checkt auf gültige Links

### ISSUE THREAD

**Issue by thenickless** [RRZE-Webteam/rrze-shorturl#123]
Respond 4xx => Link-Paar deaktivieren

**Comment by xwolfde** [comment]
Bitte hier nochmal prüfen, ob es Probleme gibt.

Leider wurden Links auf z.b. intern.fau.de gemacht. Diese Site ist jedoch hinter einem SSO Schutz.
Ansonsten sind die Links jedoch korrekt.
Frage: Wie wird in solchen Fällen der Checker auf ungültige Links nun reagieren?
ggf. bei einem Status "Forbidden" nicht löschen, sondern nur wenn tatsächlich der Status "File not Found" ist?

Es wäre ungut, wenn solche Links nun gelöscht werden.
Gleichzeitig kann man nicht den Checker Zugriff auf jede interne Website geben. Vorallem da wir das ja nicht vor dem Check wissen, ob Zieladresse "intern" oder Passwortgeschützt ist. Derjenige, der sie einträgt, kann drauf zugreifen...

**Comment by xwolfde** [comment]
wie besprochen: 
Kein Prüfmechanismus mehr (auskommentieren)
