### ISSUE TITLE
Eigener URI-Link nicht bearbeitbar und nicht löschbar

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-shorturl#130]
Ich hab Montag den URI-Link /faudir angelegt.

![grafik](https://github.com/user-attachments/assets/53789178-489b-448b-a928-b75e66d1ac9c)

Jetzt taucht der nicht unter "meine Links" auf und ich kann den auch nicht löschen oder bearbeiten.

Ich sehe auch nicht, unter welcher Kennung der angelegt wurde, was nützlich wäre, wenn es jemand anders angelegt worden wäre und ich als Admin (nicht als normaler User!) da nachfragen wollte.

**Comment by xwolfde** [comment]
neben dem Problem dass ich meinen eigenen Link nicht löschen oder bearbeiten kann, wäre es ggf. ein Enhancement-Request: Wir als Website-Admins sollten die Option haben, alle Shorturls zu löschen oder zu bearbeiten.

**Comment by thenickless** [comment]
Wir haben in Live gerade ein Problem mit der Rückgabe von rrze-ac beim SSO. Und zusätzlich gibt es einen Bug im Handling des String mit der IdM, denn die Datenbank ist so ausgelegt, dass ein Contraint greifen würde, wenn man IdM mehrfach inserten wollen würde, weshalb deine doppelte Kennung vermutlich ein Space oder ähnliches enthält.

<img width="1502" alt="Bildschirmfoto 2024-07-18 um 12 56 26" src="https://github.com/user-attachments/assets/7f0cfcb9-dcc4-4246-805f-8076998f30b9">

**Comment by thenickless** [comment]
Meine große Herausforderung dabei ist, dass ich keinen Zugriff auf die Datenbank durch zB PHPmyAdmin habe und mir Tools basteln muss, die mir SQL Rückgaben zeigt. Ich kann somit nicht einfach mal eben nachgucken, welcher Link wem gehört oder ein Test-SQL vorab ohne Datenbank-Commit absetzen.

**Comment by xwolfde** [comment]
Geht mir genauso und bei meinen Plugins machte ich auch immer dasslebem it Debugging... Selbst wenn man den MyAdmin-Zugang hat, muss man sich durch Tausend-Subtables wühlen, was eigentlich immer mehr Zeit kostet als den "Umweg" über eigenes Debugging im Plugin.

**Comment by thenickless** [comment]
Naja, ich find SQL schon nützlich und wühle mich nicht durch Subtables. Bei diesem habe ich die Tables, Contraints, Trigger etc selbst angelegt, an der Struktur hapert's nicht. Ich ist halt kompliziert mit Plugin in Git, merge, auf CMS update mit einigen Klicks, refresh ggfalls unterschiedlichste Caches zu refreshen, in der console hoffen, dass man nichts vergessen hat, damit man das ganze Prozedere erneut machen muss. Im Ideal(!) ist Testumgebung IDENTISCH mit Liveumgebung. Dies ist bei uns aus bekannten Gründen nicht der Fall. SSO Test-IdP liefert über rrze-ac anderes als die Live-IdP. Ich komm aber auch aus der Oracle Welt. Vor Internet habe ich als Oracle DB gearbeitet und mag PL/SQL und SQL gleichermaßen.

**Comment by thenickless** [comment]
1.9.0 : Fehler taucht nicht mehr auf.
