### ISSUE TITLE
Service-URL zu Zoom fehlerhaft

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-shorturl#131]
Wollte einen Zoomraum als ShortURL eintragen, erhielt aber den Fehler:

<img width="1005" alt="grafik" src="https://github.com/user-attachments/assets/dc6c4923-d292-4718-9262-ddcb28e00979">

Beim Aufruf der vorgeblichen ShortURL  /2a  kam man zwar zu Zoom, aber dort mit falscher Id:

<img width="1005" alt="grafik" src="https://github.com/user-attachments/assets/235e476f-b4e1-4f3e-9954-2c03a6a4ca45">

Was ein Blick in die Redirection auch bestätigt:
<img width="546" alt="grafik" src="https://github.com/user-attachments/assets/792e0e49-4995-4565-a35e-b867fa504943">

Als Services ist im Backend als RegEx eingetragen:
`https://fau.zoom-x.de/j/$nr`

$nr wurde hier falsch als 1 gesetzt, obwohl die eingegebene Nummer eine andee war.

Ausserdem fehlt wohl auch der GET-Parameter, der bei Zoom-Räumen auch dabei ist.

Die _Fehlermeldung_/Warnung beim Erstellen ist immer noch unschön und sollte so nicht mehr erscheinen.

**Comment by thenickless** [comment]
Mit 1.9.0 erledigt.

(Zoom-Links sind "Externe Links" und keine "Service Links", da sie unterschiedliche GET-Parameter enthalten, die nicht automatisch identifiziert werden können. Bsp "pwd".
