### ISSUE TITLE
Liste der ShortURLs und Bearbeiten

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-shorturl#145]
Beim Aufruf der Funktion "Liste an ShortURLs" sehe ich erstmal nur meine eigenen Links:
![grafik](https://github.com/user-attachments/assets/94837812-0366-486f-b7ae-daae6cfcfe1f)

Das ist gut so.

Wenn ich dann auf Bearbeiten klicke, hab ich plötzlich alle gefühlte Tausende ShortURLs oben.
 
<img width="1640" alt="grafik" src="https://github.com/user-attachments/assets/cb7b5480-cd67-44a8-ae05-585b0b206515">

Bitte es so machen, dass beim Bearbeiten eines Links auch nur die eigenen Links sichtbar sind.

Eigentlich muss man ohnehin nicht die anderen Links fremder Leute sehen. Der Mehrwert ist sehr gering.
Daher ggf. es so machen, dass man grundsätzlich die Links anderer nicht sehen kann, auch nicht über eine Optikn "Alle anzeigen" o.ä..

Dann wird dieser issue "mitgelöst".

**Comment by thenickless** [comment]
@xwolfde 

"Eigentlich muss man ohnehin nicht die anderen Links fremder Leute sehen. Der Mehrwert ist sehr gering.
Daher **ggf**. (..)"

Bitte spezifizieren. Es war gewünscht, dass alle Links, auch die fremder Leute zu sehen sind. Darum die Checkbox. Ich kann es freilich problemlos so umsetzen, dass es keine Checkbox "Nur meine Links" gibt und immer nur die eigenen Links angezeigt werden und die Checkbox erscheint, wenn man eingeloggt als Admin ist. Ich kann dabei auch den bisherigen Code nur auskommentieren und nicht direkt löschen, wenn es dann doch zweckmässig ist, dass alle User alle Links sehen können. Welche editiert werden können, ist bereits berücksichtigt: nur die eigenen.

"**gegebenenfalls**" ist hierbei zu unscharf für mich. ;-) 

Kurz:
Soll ich es erstmal im Code auskommentieren und so  umsetzen, wie du es jetzt in diesem Issue geschrieben hast?
Admins sollen dabei immer alle Links sehen und editieren können (so der letzte Info-Stand) => das beibehalten?

**Comment by thenickless** [comment]
@xwolfde 

Alles gut, hab's nicht als Vorwurf verstanden. Ich bin dran. BTW, gerade weil es ein Plugin ist, das weitestgehend Funktionalität im Frontend bereitstellt, die für gewöhnlich im Backend gehandhabt werden, hatte ich mich (mit dem OK von Rof) für eine Datenbank-Lsg entschieden, die mittels Constraints & Triggern (wobei die Trigger redundant wurden), auf bestmögliche Performance ausgerichtet ist. Es ist ein deutlicher Unterschied zwischen zB "INSERT ... ON DUPLICATE KEY UPDATE ..." mehreren WP_Query mit meta_query(s), um Datenkonsitenz zu gewährleisten ... ist long_url da, ist short_url bereits errrechnet, ist uri unique, ... (disclamer: kein Vorwurf, nur eine Erklärung meines Denkansatzes beruhend auf a la "Tut, wie ihr meint, mit den Tools eurer Wahl, Hauptsache es läuft und das schnell." :-D Aber ich habe es freilich refactored https://github.com/RRZE-Webteam/rrze-shorturl/issues/132 Dass die CPT im Backend bewusst nicht sichtbar sind, liegt daran, dass alles im Frontend läuft und ein einfaches show_ui, show_in_menu reicht da nicht. Gerade bei IdM muss aufgepasst werden. Aber vor allem, weil es ja alles nur Meta-Daten sind, die aber dennoch datenkonsitent gespeichert werden müssen, was WordPress so nicht bietet. Ich bin aber dran, dass alles so läuft, wie gewünscht. Ist kein großer Aufwand mehr.
