### ISSUE TITLE
Tabelle der Liste der ShortURLs ändern

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-shorturl#146]
- Bitte die Spalte "URI" ersatzlos entfernen für alle User.
- Tabellenbeschriftung ändern:
     -  "Langer URL" -> "Zieladresse" 
     -  "Kurz-URL" -> "ShortURL"
     

Wenn ein ShortURL ausnahmsweise eine URI hat, dann diese in der Zelle Kurz-URL als zusätzliche URL (break zwischen beiden) schreiben.

(Die Existenz der Funktion von sprechenden URLs bitte grundsätzlich möglichst verbergen. Leider gibt es bereits jetzt viele Anfragen dazu, die uns nur Zeit kosten. Daher am Besten garnicht erst erwähnen, dass es diese Option gibt)

**Comment by thenickless** [comment]
@xwolfde 

"Wenn ein ShortURL ausnahmsweise eine URI hat, dann diese in der Zelle Kurz-URL als zusätzliche URL (break zwischen beiden) schreiben."

Bislang gibt es je einem langen Link einen kurzen.

Kann das beibehalten werden oder soll es bei "selbsterklärende URI" zwei verkürzte Links geben - einen mit selbsterklärende URI und einer der berechnet wurde.

**Comment by xwolfde** [comment]
Den langen (Zieladresse) beibehalten und weiter anzeigen. Nur dort die Tabellenzelle in der die berechnete URL ist, die mit der sprechenden URI als zweite URL ergänzen. => Damit wir die Tabellenspalte mit der URI sparen

**Comment by thenickless** [comment]
Bisher gab es pro Zieladresse **einen** ShortURL, unabhängig davon, ob die URI automatisch generiert oder vom Kunden selbst vergeben wurde.

**Beispiele bisher:**

a) 
[https://go.fau.de/werkstoff](https://go.fau.de/werkstoff) → [https://meinstudium.fau.de/studiengang/advanced-materials-and-processes-msc/](https://meinstudium.fau.de/studiengang/advanced-materials-and-processes-msc/)

b) 
[https://go.fau.de/1eh](https://go.fau.de/1eh) → [https://meinstudium.fau.de/weg-an-die-fau/](https://meinstudium.fau.de/weg-an-die-fau/)

---

Soll es in Zukunft **zwei** ShortURL geben, wenn die URI vom Kunden vergeben wurde?

**Beispiel für zukünftige Links:**

a)  
[https://go.fau.de/werkstoff](https://go.fau.de/werkstoff) → [https://meinstudium.fau.de/studiengang/advanced-materials-and-processes-msc/](https://meinstudium.fau.de/studiengang/advanced-materials-and-processes-msc/)  
Neu: https://go.fau.de/1xyz → [https://meinstudium.fau.de/studiengang/advanced-materials-and-processes-msc/](https://meinstudium.fau.de/studiengang/advanced-materials-and-processes-msc/)

b)  
[https://go.fau.de/1eh](https://go.fau.de/1eh) → [https://meinstudium.fau.de/weg-an-die-fau/](https://meinstudium.fau.de/weg-an-die-fau/)
