### ISSUE TITLE
cron alle 5 min für .htaccess Generierung

### ISSUE THREAD

**Issue by thenickless** [RRZE-Webteam/rrze-shorturl#26]
am besten in den Settings einstellbar machen

Rückgabe: lief glatt, Errors mit Timestamp anzeigen.

**Comment by xwolfde** [comment]
Bitte drauf achten (wenn noch nicht geschehen), nur in einem bestimmten Bereich der .htaccess zu schreiben / zu ergänzen, so daß in der .htaccess auch andere Anweisungen stehen können.
D.h. z.B. Einträge nur zwischen 
```
# BEGIN SHORTCODE-DB
...
#END SHORTCODE-DB

```
zu schreiben.

**Comment by thenickless** [comment]
Das ist natürlich selbstverständlich. Ich überbügle doch keine .htaccess! :-D
Siehe https://github.com/RRZE-Webteam/rrze-shorturl/blob/ae69ec05859718f7b2309a88dae02975fe4a8c87/make_htaccess.php#L33
.htaccess ist so ziemlich das Sensibelste in der Webentwicklung. :^}

**Comment by thenickless** [comment]
die .htaccess Generierung ist außerhalb vom Plugin. Es wird nur das Script dafür mitgeschickt, das in einer Crontab aufgerufen wird. Darum schließe ich hier das Issue. Einstellung in settings ist auch nicht nötig. Das macht ein SysAdmin mit 

```
crontab -e

*/5 * * * * php /path/to/your/script/make_htaccess.php

```
