### ISSUE TITLE
Optionale SSO-Login für definierte Personen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-shorturl#5]
Optionale SSO-Login für definierte Personen, die das Recht haben, individuelle ShortURLs zu generieren. 
Die erlaubten Gruppen, die ShortURLs bearbeiten können, sollen zunächst beschränkt sein, können aber später auf FAU Affilation Gruppen erweitert werden.

**Comment by thenickless** [comment]
umgesetzt in 0.1.59
