### ISSUE TITLE
Definition und Bearbeiten von ShortURLs

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-shorturl#6]
Berechtigte Benutzer sollen folgende Informationen zu einer neuen ShortURL eingeben können:

- Zieladresse (URL ohne GET-Parameter; nur berechtigte Benutzer, vgl #7  haben zusätzlich die Option selbst GET-Parameter anzugeben)
- Gültigkeitsdauer (Datumsfeld, bis wann der EIntrag erhalten bleiben soll. Per Default sollte keine URL länger als 1 Jahr gültig bleiben. Nur besonders berechtigte Nutzer sollen eine längere  Lebensdauer festlegen können. Welche Benutzer berechtigt sind, könnte über die Plugin-Settings gesteuert werden. Indem dort die IdM-Kennung dieser User jeweils gespeichert wird).
- Optional: Kommentarfeld mit Notizen zum ShortURL
- Optional: Kategorie
- Optional: Tags
- Nur für besonderes berechtigte Benutzer sichtbar/speicherbar: Eingabefeld für eine sprechende URI.

Sowie intern ohne EIngabefelder:
- Benutzerkennung
- Anlegedatum

Bei der EIngabe der Daten wird stets überprüft ob die Ziel-Adresse (Domain) erlaubt ist, gemäß #3 .

Nach der erfolgreichen EIngabe erhält der Benutzer die ShortURL angezeigt. Die ShortURL berechnet sich aus der Id des Eintrags, sowie eines Prefixes. Wenn das EIngabefeld für eine sprechende URI aufgrund von Berechtigungen eingegeben werden konnte. wird zusätzlich die eingegebene URI als Shorturl ermöglicht.

Weiterhin wird ein QR-Code angeboten (downloadbar als Bild), den der Benutzer sich für andere Systeme oder Publikationen kopieren kann.

Bei EIngabe einer sprechenden URI muss darauf geachtet werden, dass keine Page/Post oder anderees Objekt mit diesem Slug existiert und ob es diese URI schon gibt.

**Comment by thenickless** [comment]
umgesetzt in 0.1.59
