### ISSUE TITLE
URLs mit Fehlern: Fehlermeldung mit Ansprechpartner versehen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-shorturl#73]
Wenn eine URL abgelehnt wird, weil dort eine der 3 Rechtstexte fehlen, wird momentan nur ausgegeben was fehlt und das es jetzt halt nicht geht.
Es wäre schön, auch um Supportanfragen bei uns zu reduzieren udn diese an den zuständigen Webmaster zu kanalisieren, wenn dort zusätzlich noch ergänzt wird, wer der Wbemaster der Website ist und wie man diesen erreicht.

Also bspw. so:

```
Auf die Webseite kann derzeit keine ShortURL erstellt werden, da das/die (Impressum|Datenschutzerklärung|Barrierefreiheitserklärung) fehlt.
Um diesen Fehler beheben zu lassen, können Sie sich an den technischen Ansprechpartner der betreffenden Website wenden: <a href="mailto:maildresse">Vorname Nachname &lt;mailadresse&gt;</a>
```

Den Webmaster kann man über die API vom WMP abrufen. Hierzu ggf. Max ansprechen.

**Comment by thenickless** [comment]
so geht's:
Class CustomerDomains plus https://www.wmp.rrze.fau.de/suche/impressum/www.rrze.fau.de/format/json
