### ISSUE TITLE
Doku ggfalls ergänzen

### ISSUE THREAD

**Issue by thenickless** [RRZE-Webteam/rrze-shorturl#79]
https://blogs.fau.de/webredaktion/kurzadressen-der-zuv/

**Comment by xwolfde** [comment]
Die Seite ist von 2018.
(Und heite hab ich die gefragt ob die das Blog überhaupt noch nutzen).

Warten wir es mal ab. Mein Ziel wäre eher, dass wir fau.info auch noch übernehmen mit den Shorturl-Service.
