### ISSUE TITLE
Schönere Meldung bei Service-URLs

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-shorturl#80]
Diese Meldung sieht ein bißchen frech aus, weil es als "Error" gemeledet wird.
Es ist aber kein Error, den als Anwender kriegt man ja die kurze URL eben nirgends bei Zoom gezeigt.

![grafik](https://github.com/RRZE-Webteam/rrze-shorturl/assets/1070669/5afaf1d1-615a-47fd-8271-07ca2e7b7775)

Mach es in diesem Fall der Service-URLs doch so, dass hier keine erweiterten Einstellungen möglich sind, aber dafür trotzdem die normale erolgreiche Ausgabe der ShortURL und des QR Codesangezeigt werden, als wie es bei den anderen URLs auch der Fall ist.

**Comment by thenickless** [comment]
Ist in 1.5.0 umgesetzt

Service URLs haben wie auch eine erweiterte EInstellung und berechtigte User können darüber einen URI eingeben. (+  Gültigkeitsdatum, Kategorie) -> https://github.com/RRZE-Webteam/rrze-shorturl/issues/91
