### ISSUE TITLE
Service Zoom geht noch nicht so richtig?

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-shorturl#81]
Diese URL
https://go.fau.de/2a-r3ur9q
liefert eine Fehlermeldung.

Sollte auf
https://fau.zoom-x.de/j/96237382893
gehen

**Comment by thenickless** [comment]
da fehlte in den Settings die RexEx. Ist jetzt gespeichert: https://fau.zoom-x.de/j/$nr und es geht. Kommt gleich noch als Default in die config.php
