### ISSUE TITLE
Spezielle externe Domains erlauben?

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-shorturl#82]
Aktuell schauen wir ja bei den Domains darauf, das dies enur von uns gepflegt werden, sieht man von den Services ab.

Wäre es denkbar, wenn wir doch eine Liste (im Backend) pflegen an Domains, die trotzdem erlaubt sind?
Beispielsweise [youtube.com](https://www.youtube.com/watch?v=dQw4w9WgXcQ)

**Comment by thenickless** [comment]
oder besser: 
fau-shop.de & co
und
youtube & co

in "others". Gleiche Funktionalität und streng genommen sind das ja nicht unsere Services.

**Comment by thenickless** [comment]
done 1.6.0

Neuer Reiter "Externe Domains"
