### ISSUE TITLE
UI/UX "Erweiterte Einstellungen"

### ISSUE THREAD

**Issue by thenickless** [RRZE-Webteam/rrze-shorturl#90]
_Hatte gerade VC mit @xwolfde_ : @cassandre kannst du bitte überlegen, ob der Overlay mit den erweiterten Einstellungen, wie er jetzt ist, gut ist oder ob es besser wäre, den Content darin unterhalb auf der Page nach Klick auf "erweiterte Einstellungen" anzuzeigen und einen Overlay nicht zu verwenden?

Ich finde die derzeitige Lsg gut, weil es

- Barrierefrei ist (kann mit Tastatur bedient werden)

- supersimpel einzubauen war (kannte ich noch nicht. Cool, wie das geht. Leider wird es noch nicht von allen Browsern unterstützt)

- es ein bisschen den Touch von einer App hat

- den Fokus auf den Bereich lenkt

- es einfacher ist, ein Visual Feedback einzubauen. Es gibt ja keinen Save Button darin und das soll auch so bleiben, aber dass danach auf den Shorten-Button geklickt werden muss, muss entweder angezeigt werden, oder ich häng das an den Event/Trigger ran, der greift, sobald der Overlay geschlossen wird (geht sogar mit der Escape-Taste. I love it 😄 )
Andererseits ist ein Visual Feedback unnötig, wenn das alles auf einer Page ist. 
Beibehalten wird in jedem Fall, dass es KISS ist: mit nur einem einzigen Input und einem Button und sonst nichts. Alles weitere wird nur dann angezeigt, wenn User das brauchen.

Sollten wir beim Overlay bleiben, verschönere bitte den Content darin. Der Abstand zum Rand kommt mir zu breit vor, der Rand ist mMn zu breit, ... das sieht insgesamt nicht stimmig vom Design her aus.

_Vielleicht nicht ohnehin klar: der Content in dem Overlay kann lang werden. Es können beliebig viele Kategorien angelegt werden (samt Children) und da die mit Checkbox ausgewählt werden können, müssen die angezeigt werden. Ggfall Scrollbar, aber vielleicht wird schon jetzt eine angezeigt, hab's noch nicht getestet._

**Comment by cassandre** [comment]
Ah, den Gedanken hatte ich auch schon, habe mich aber nicht getraut nachzufragen. Ich fände ein auf-slidendes Div auf jeden Fall viel besser.
Ansonsten sieht der Overlay mittlerweile sowieso so aus:
<img width="831" alt="Bildschirmfoto 2024-05-28 um 21 29 06" src="https://github.com/RRZE-Webteam/rrze-shorturl/assets/4435815/5ae82d16-f362-4771-ad54-e745117bd80a">

**Comment by thenickless** [comment]
https://github.com/RRZE-Webteam/rrze-shorturl/issues/90#issuecomment-2135966141

Nice. Bleibt das zentriert, wenn viele Categories enthalten sind?

Du fändest ein auf-slidendes DIV auf jeden Fall viel besser?
Bitte setze es einfach um. @cassandre  Es wird uns bestimmt überzeugen. :-D  Bin neugierig auf deine Begründung. Ich kann mir jetzt gerade nicht vorstellen, dass das hinhaut bei einer langen Liste .. wo sind dann die Buttons?

**Comment by cassandre** [comment]
> Nice. Bleibt das zentriert, wenn viele Categories enthalten sind?

Ja, und wird scrollbar, wenn die Kategorienliste länger als der Bildschirm ist.

> Du fändest ein auf-slidendes DIV auf jeden Fall viel besser? Bitte setze es einfach um. @cassandre Es wird uns bestimmt überzeugen. :-D Bin neugierig auf deine Begründung. Ich kann mir jetzt gerade nicht vorstellen, dass das hinhaut bei einer langen Liste .. wo sind dann die Buttons?

Link-Input
darunter Erweitert-Button, der das Erweitert-Div öffnet
darunter den Shorten-Button

D.h. wenn die erweiterten Einstellungen geöffnet sind, kann man entweder ganz nach unten scrollen, oder das Erweitert-Div wieder schließen (wie beim Accordion), bevor man unten zum Shorten-Button kommt

**Comment by thenickless** [comment]
@cassandre Danke! Es ist toll geworden! Und die Benutzerfreundlichkeit ist verbessert mit dem aufgeräumten Design und es kann beliebig nach unten wachsen. Leider geht alles derzeit nur auf FF, nicht auf zB Safari, aber da müssen die Browseranbieter mal Gas geben.
